services:
  django:
    build: ./backend
    networks:
      - django_net
      - redis_net
      - db_net
    # volumes:
    env_file:
      - .env
    depends_on:
      - redis
      - postgresql
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    networks:
      - redis_net
    ulimits:
      nofile:
        soft: 10032
        hard: 10032

  postgresql:
    image: postgres:16-alpine
    hostname: localhost
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - db_net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - 8000:8000
    networks:
      - django_net
    depends_on:
      - django
    volumes:
      - ./frontend:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    restart: unless-stopped

volumes:
  data:
  postgres-data:

networks:
  django_net:
  redis_net:
  db_net:
