services:
  django:
    build: ./backend
    networks:
      - django_net
      - db_net
    # volumes:
    env_file:
      - .env
    depends_on:
      - postgresql
    restart: unless-stopped

  postgresql:
    image: postgres:16-alpine
    networks:
      - db_net
    # volumes:
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - 8000:8000
    networks:
      - django_net
    depends_on:
      - django
    volumes:
      - ./frontend:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    restart: unless-stopped

volumes:
  data:

networks:
  django_net:
  db_net:
