services:
  django:
    build: ./services/django
    ports:
      - 8000:8000
    networks:
      - backend_net
    # volumes:
    env_file:
      - .env
    depends_on:
      - postgresql
    restart: unless-stopped

  postgresql:
    image: postgres:15
    # build: ./services/postgresql
    networks:
      - backend_net
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_vol:

networks:
  backend_net:
