services:
  django:
    build: ./backend
    networks:
      - django_net
      - redis_net
      - db_net
    volumes:
      - django_statics:/app/static
    env_file:
      - .env
    depends_on:
      - redis
      - postgresql
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    networks:
      - redis_net
    ulimits:
      nofile:
        soft: 10032
        hard: 10032

  postgresql:
    image: postgres:16-alpine
    networks:
      - db_net
    # volumes:
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - 8000:8000
    networks:
      - django_net
    depends_on:
      - django
    volumes:
      - ./frontend:/var/www/html/
      - django_statics:/var/www/django
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    restart: unless-stopped

volumes:
  django_statics:
  data:

networks:
  django_net:
  redis_net:
  db_net:
