FROM postgres:16-alpine
WORKDIR /home/nwai-kea/42KL-23-Ft_Transcendence/services/postgresql/
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-16 postgresql-client-16 postgresql-contrib-16
COPY *.sql /docker-entrypoint-initdb.d/
EXPOSE 5432